#!/usr/bin/env python
"""Generate Hill 395 ablation configs as COPIES of cita_full_hill395.yaml.

The base config is never modified. Each variant is the base with exactly one
component changed (single-factor ablation), written to configs/ablation/.
blocking settings (dt_max, grid_cell, r_err_floor, type_by_category) are left
identical to the base in every variant, by construction.

    python scripts/gen_ablation_configs.py

Variant families
  1A stage   : m1 (no graph, no decoder) -> m2 (+graph) -> m3_full (+decoder = base)
  1B CTA LOO : drop one of {time,motion,state,rel,src} from cta.enabled_terms.
               NOTE: 'sem' is NOT a CTA leave-one-out target -- the semantic
               cosine (w0*sim) is the always-on base score, not a gated term, and
               semantic signal also reaches the pair head via the encoder
               embeddings + p_text_cos, so dropping 'sem' here is a no-op. So the
               LOO is 5-way (no no_sem). (Confirmed in src/citanet/model/cta.py.)
  1C loss    : zero lambda_trajectory / lambda_assign (optional).
"""
from __future__ import annotations

import copy
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
BASE = REPO / "configs" / "cita_full_hill395.yaml"
OUT_DIR = REPO / "configs" / "ablation"

FULL_TERMS = ["sem", "time", "motion", "state", "rel", "src"]


def _variant(base: dict, stage: str, mutate) -> dict:
    cfg = copy.deepcopy(base)
    cfg["stage"] = stage
    mutate(cfg)
    return cfg


def build_variants(base: dict) -> dict[str, dict]:
    v: dict[str, dict] = {}

    # ---- 1A: stage ladder (architecture) ----
    def m1(c):
        c["graph"]["enabled"] = False
        c["decoder"]["enabled"] = False

    def m2(c):
        c["graph"]["enabled"] = True
        c["decoder"]["enabled"] = False

    def m3(c):
        c["graph"]["enabled"] = True
        c["decoder"]["enabled"] = True

    v["m1"] = _variant(base, "cita_full_hill395_m1", m1)
    v["m2"] = _variant(base, "cita_full_hill395_m2", m2)
    v["m3_full"] = _variant(base, "cita_full_hill395_m3_full", m3)

    # ---- 1B: CTA leave-one-out (from m3_full) ----
    for term in ["time", "motion", "state", "rel", "src"]:
        terms = [t for t in FULL_TERMS if t != term]

        def loo(c, terms=terms):
            c["graph"]["enabled"] = True
            c["decoder"]["enabled"] = True
            c["cta"]["enabled_terms"] = terms

        v[f"no_{term}"] = _variant(base, f"cita_full_hill395_no_{term}", loo)

    # ---- 1C: loss ablation (from m3_full) ----
    def no_ltraj(c):
        c["graph"]["enabled"] = True
        c["decoder"]["enabled"] = True
        c["loss"]["lambda_trajectory"] = 0.0

    def no_lassign(c):
        c["graph"]["enabled"] = True
        c["decoder"]["enabled"] = True
        c["loss"]["lambda_assign"] = 0.0

    v["no_ltraj"] = _variant(base, "cita_full_hill395_no_ltraj", no_ltraj)
    v["no_lassign"] = _variant(base, "cita_full_hill395_no_lassign", no_lassign)

    return v


def main() -> None:
    base = yaml.safe_load(BASE.read_text(encoding="utf-8"))
    # The base config must explicitly carry graph/decoder/cta blocks so the
    # generated variants override real values (not silently rely on defaults).
    base.setdefault("graph", {})
    base.setdefault("decoder", {})
    base.setdefault("cta", {})
    base.setdefault("loss", {})
    base["cta"].setdefault("enabled_terms", list(FULL_TERMS))

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    variants = build_variants(base)
    for name, cfg in variants.items():
        path = OUT_DIR / f"{name}.yaml"
        header = (f"# GENERATED by scripts/gen_ablation_configs.py from "
                  f"configs/cita_full_hill395.yaml -- do not edit by hand.\n"
                  f"# Variant: {name}  (single-factor ablation; blocking identical to base)\n")
        path.write_text(header + yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True),
                        encoding="utf-8")
        print(f"wrote {path.relative_to(REPO)}  "
              f"(graph={cfg['graph'].get('enabled')}, decoder={cfg['decoder'].get('enabled')}, "
              f"terms={cfg['cta'].get('enabled_terms')})")


if __name__ == "__main__":
    main()
